name: Build Openwrt
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4
      
      - name: 更新系统环境和安装必要依赖
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
          genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
          libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
          python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
          swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
      
      - name: 拉取仓库源码
        run: |
          git clone https://github.com/hiuliuli/lede
      
      - name: 更新feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: 复制.config文件
        run: |
          cp .config lede/
      
      - name: 下载dl库
        run: |
          cd lede
          make defconfig
          make download -j8
      
      - name: 编译固件
        run: |
          cd lede
          make V=s -j$(nproc)
      
      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          path: lede/bin/targets/**/*.gz
          if-no-files-found: warn

